/**
 * Factory that takes a recipe data object as parameter and returns an object with
 * a function that will generate the DOM element for the recipe card
 *
 * @param {object} data - The recipe data object from which the recipe card info will be extracted
 * @returns {object} - An object with a function that returns a DOM element for the recipe card
 */
export function recipeCardFactory(data) {
  const { name, ingredients, time, description } = data;

  /**
   * Returns a string of the innerHTML that will be used to create the recipe card header
   *
   * @returns {string} recipeCardHeaderDOM - A variable with the innerHTML of the recipe card header
   */
  function getRecipeCardHeaderDOM() {
    const recipeCardHeaderDOM = `
    <div class="recipes-card-header">
        <p class="recipes-card-title">${name}</p>
        <div class="recipes-card-duration">
            <i class="fa-regular fa-clock"></i>
            <p>${time} min</p>
        </div>
    </div>
    `;
    return recipeCardHeaderDOM;
  }

  /**
   * Returns a string of the innerHTML that will be used to create the recipe card description
   *
   * @returns {string} recipeCardDescDOM - A variable with the innerHTML of the recipe card description
   */
  function getRecipeCardDescDOM() {
    let recipeCardIngredients = "";

    ingredients.forEach((element) => {
      const recipeName = element.ingredient;
      const recipeQty = element.quantity ? element.quantity : "";
      const recipeUnit = element.unit ? element.unit : "";

      recipeCardIngredients += `
        <li class="recipes-card-ingredients-item">
            <p class="recipes-card-ingredients-name">${recipeName}:</p>
            <p class="recipes-card-ingredients-qty">${recipeQty} ${recipeUnit}</p>
        </li>
        `;
    });

    const recipeCardDescDOM = `
    <div class="recipes-card-desc">
        <ul class="recipes-card-ingredients">
        ${recipeCardIngredients}
        </ul>
        <p class="recipes-card-todo">${description}</p>
    </div>
    `;

    return recipeCardDescDOM;
  }

  /**
   * Generates the DOM element for the recipe card using the innertHTML generated by the
   * getRecipeCardHeaderDOM() and getRecipeCardDescDOM() functions then returns it as an object
   *
   * @returns {object} listitem - An object with the DOM element for the recipe card
   */
  function getRecipeCardDOM() {
    const listitem = document.createElement("li");
    listitem.className += "recipes-card";

    const recipesCardImg = document.createElement("div");
    recipesCardImg.className += "recipes-card-img";

    const recipesCardInfo = document.createElement("div");
    recipesCardInfo.className += "recipes-card-info";

    recipesCardInfo.innerHTML += getRecipeCardHeaderDOM();
    recipesCardInfo.innerHTML += getRecipeCardDescDOM();

    listitem.append(recipesCardImg);
    listitem.append(recipesCardInfo);

    return listitem;
  }

  return { getRecipeCardDOM };
}
